### ISSUE TITLE
neutral inductive form printing incorrect

### ISSUE THREAD

**Issue by pnwamk** [the-little-typer/pie#13]
https://github.com/the-little-typer/pie/blob/28fe6d4bb1df0fbdb84e9a2bdb8106e60fbfe2bf/pretty.rkt#L154

Targets of induction are printed at the tail end of the s-expression instead of at the head.

I played around with a potential fix but it seemed like there might be some creative decision making that @david-christiansen  would be better suited to address (i.e. if there are two targets, are they printed on the same line as the induction form? If so... what if they span multiple lines (i.e. because they are large neutral terms as well)... etc)

**Comment by david-christiansen** [comment]
Blagh. This whole pretty-printer is a bit of a quick hack, and should really be replaced by something more principled. Thanks for the report - do you have a concrete example that demos the breakage?

**Comment by pnwamk** [comment]
Yah sorry -- I'll add an example and/or screenshot.

I'm currently in the weeds on a proof trying to figure out why it's not "just true" XD

**Comment by pnwamk** [comment]
Before I forget, neutral cong is also broken w.r.t. printing -- it doesn't print the target of elimination, it prints the type of the equality and the function. I'll submit a issue for that separately later.

**Comment by david-christiansen** [comment]
I think this is fixed now. Can you test it on your examples to make sure?

Thanks again!

**Comment by pnwamk** [comment]
It looks great -- thanks!
