### ISSUE TITLE
confusing error message on (4)

### ISSUE THREAD

**Issue by jbclements** [the-little-typer/pie#25]
When I run this program (or many other syntactically invalid programs):

```
#lang pie

(4)
```

... I get the error message 

```
?: expected more terms starting with rand
  parsing context: 
   while parsing application in: (4)
```

I don't understand what 'rand' has to do with this situation. Could this error message be improved?

Thanks!

**Comment by david-christiansen** [comment]
New message:
```
?: expected more terms starting with first argument
  parsing context: 
   while parsing function application in: (4)
```

Thanks!
