### ISSUE TITLE
Syntax highlighting for vim

### ISSUE THREAD

**Issue by felipesere** [the-little-typer/pie#26]
Its very rough and quickly whopped together, but this vim plugin makes it nice to work with `pie`.
I'd be happy to hand this over to `the-little-typer` if you want to take it further than I can.

https://github.com/felipesere/pie-highlight.vim

Here is a screenshot with my vim them:
<img width="716" alt="screenshot 2018-11-14 at 20 16 29" src="https://user-images.githubusercontent.com/1850188/48520368-4663f980-e868-11e8-8589-8a25228a90b8.png">

**Comment by david-christiansen** [comment]
Hello! Thanks for writing this!

I'm in no way qualified to maintain Vim syntax highlighting. Do you mind if I add a link to your highlighting in the README?

Thanks again!

**Comment by felipesere** [comment]
👍 I’ll open a PR shortly

**Comment by david-christiansen** [comment]
Closing due to a few months without reply.
