### ISSUE TITLE
Super-simple doc typo (#10 redux)

### ISSUE THREAD

**Issue by jbclements** [the-little-typer/pie#27]
Looks like #10 addressed the type given in the header, but not the type listed in the explanation. 

Specifically:

The `cong` documentation states that cong returns a 

(= Y (fun from) (fun to))

I believe this is correct. The last line of the explanation, though, says 

"then (cong target fun) is an
(= X (fun from) (fun to))”

I believe this should instead read

"then (cong target fun) is an
(= Y (fun from) (fun to))”

(note the replacement of X with Y).

Thanks!

John

**Comment by david-christiansen** [comment]
You're exactly right. Thanks!

**Comment by david-christiansen** [comment]
Fixed in e3579c2.
