### ISSUE TITLE
+, which nat etc not available?

### ISSUE THREAD

**Issue by jsalzbergedu** [the-little-typer/pie#31]
I'm trying to work through the little typer, but for some reason +, which nat etc are not defined when I do racket -I pie. Is this intentional? Thank you.

**Comment by david-christiansen** [comment]
Thanks for working so carefully through the book!

We did cheat a little bit with regards to `+`. We use it in earlier chapters, but don't define it until pages 75-76. You'll have to suspend your disbelieve a little bit with regards to that, or paste the following into your file:
```
(claim +
  (-> Nat Nat
    Nat))
(define +
  (lambda (n j)
    (iter-Nat n j
      (lambda (sum)
        (add1 sum)))))
```
and then wait until page 75 for it to make sense.

`which-Nat`, on the other hand, is a built-in part of Pie. I'm not sure why you'd get a message that it isn't available. Can you paste a short example that triggers the message, and the message itself?

Here's how it works for me:
```
$ racket -l pie -i
Welcome to Racket v6.11.
> (which-Nat 0 't (lambda (n) 'nil))
(the Atom 't)
```

**Comment by jsalzbergedu** [comment]
I didn't see the capitalization. My bad.

**Comment by david-christiansen** [comment]
Glad it's working for you!
